http_addr = "0.0.0.0:9636"
router_addrs = ["127.0.0.1:5562"]

[depot]
datastore_addr = "0.0.0.0:6379"

[github]
url = "https://api.github.com"
client_id = "e98d2a94787be9af9c00"
client_secret = "e5ff94188e3cf01d42f3e2bcbbe4faabe11c71ba"

[ui]
app_url          = "https://willem.habitat.sh/v1"
community_url    = "https://www.habitat.sh/community"
docs_url         = "https://www.habitat.sh/docs"
environment      = "production"
friends_only     = false
source_code_url  = "https://github.com/habitat-sh/habitat"
tutorials_url    = "https://www.habitat.sh/tutorials"
www_url          = "https://www.habitat.sh"
