http_addr = "0.0.0.0:9636"
router_addrs = ["127.0.0.1:5562"]

[depot]
datastore_addr = "0.0.0.0:6379"

[github]
url = "https://api.github.com"
# these are public, stored in this file:
# https://github.com/habitat-sh/habitat/blob/master/components/builder-api/src/config.rs#L28-L34
# we're not divulging any secrets here
client_id = "e98d2a94787be9af9c00"
client_secret = "e5ff94188e3cf01d42f3e2bcbbe4faabe11c71ba"
